const enUS_training_sentences = new Set([
  'Natural language processing is a field of artificial intelligence.',
  'Recurrent neural networks are used for sequence modeling.',
  'The quick brown fox jumps over the lazy dog.',
  'Machine learning algorithms can analyze large datasets.',
  'The Internet of Things (IoT) connects devices to the internet for data exchange.',
  'Quantum computing has the potential to revolutionize computation.',
  'Artificial neural networks attempt to mimic the human brain\'s structure.',
  'The Python programming language is widely used in data science.',
  'Einstein\'s theory of relativity transformed our understanding of space and time.',
  'In computer vision, convolutional neural networks excel at image recognition tasks.',
  'The human genome project aimed to sequence the entire human DNA.',
  'Blockchain technology underlies cryptocurrencies like Bitcoin.',
  'Shakespeare\'s plays are considered timeless classics.',
  'Climate change poses significant challenges to global ecosystems.',
  'The United Nations strives for international peace and cooperation.',
  'Renewable energy sources, such as solar and wind, are key to a sustainable future.',
  'Deep learning has achieved remarkable success in various applications.',
  'Artificial intelligence has ethical implications that require careful consideration.',
  'The Renaissance was a period of cultural and intellectual growth in Europe.',
  'Mars exploration missions seek to understand the red planet\'s geology and potential habitability.',
  'The theory of evolution by natural selection is a cornerstone of biology.',
  'Satellite technology enables global communication and navigation systems.',
  'The World Wide Web was invented by Sir Tim Berners-Lee in 1989.',
  'Cryptography plays a crucial role in securing digital communications.',
  'The Higgs boson, often referred to as the \'God particle,\' was discovered at CERN.',
  'Ancient civilizations, such as the Egyptians and Greeks, made significant contributions to human history.',
  'Machine translation has become increasingly accurate with the advent of neural language models.',
  'The periodic table organizes chemical elements based on their properties and atomic numbers.',
  'Epidemiologists study the spread and control of diseases within populations.',
  'The theory of plate tectonics explains the movement of Earth\'s lithospheric plates.',
  'Advances in quantum mechanics have led to the development of quantum technologies.',
  'The Industrial Revolution transformed society through technological innovation and industrialization.',
  'The concept of zero is a fundamental mathematical idea with deep historical roots.',
  'The Milky Way galaxy is just one of billions of galaxies in the observable universe.',
  'The Fourth Industrial Revolution is characterized by the fusion of technologies blurring the lines between physical, digital, and biological domains.',
  'The development of CRISPR-Cas9 has revolutionized genetic editing and holds great promise in biotechnology.',
  'The human brain is a complex organ that processes vast amounts of information.',
  'Sustainability practices aim to minimize the environmental impact of human activities.',
  'Cognitive psychology studies mental processes such as perception, memory, and problem-solving.',
  'The principles of democracy promote individual rights and civic participation.',
  'Astrophysics explores the properties and behavior of celestial objects in the universe.',
  'Microplastics pose a threat to marine ecosystems and require urgent attention.',
  'Behavioral economics examines how psychological factors influence economic decision-making.',
  'The concept of time dilation arises in the theory of relativity.',
  'Innovations in renewable energy technology play a crucial role in combating climate change.',
  'The importance of biodiversity lies in the variety of life forms and their ecological roles.',
  'The concept of quantum entanglement challenges classical notions of separability.',
  'Astronauts undergo extensive training to prepare for space missions.',
  'Machine learning applications range from image recognition to natural language processing.',
  'The philosophy of existentialism explores questions of individual existence and freedom.',
  'Genetic diversity is essential for the adaptation and resilience of species.',
  'The impact of social media on society raises questions about privacy and misinformation.',
  'Epidemiological models help predict the spread of infectious diseases in populations.',
  'The concept of corporate social responsibility involves businesses contributing to societal well-being.',
  'Anthropogenic activities contribute to the acceleration of climate change.',
  'The study of paleontology provides insights into Earth\'s ancient life forms.',
  'Advancements in nanotechnology have potential applications in medicine and materials science.',
  'The exploration of deep-sea ecosystems reveals diverse and unique marine life.',
  'String theory posits that fundamental particles are not points but tiny, vibrating strings.',
  'Neuroplasticity refers to the brain\'s ability to reorganize itself in response to experiences.',
  'The principles of ethics guide decision-making in various professional fields.',
  'Renowned artists throughout history have left a lasting impact on the world of art.',
  'In quantum computing, qubits can exist in multiple states simultaneously, enabling parallel computation.',
  'Psycholinguistics studies the relationship between language and cognitive processes.',
  'The principles of chemistry govern the composition and behavior of matter.',
  'Artificial intelligence in healthcare has the potential to enhance diagnostics and treatment.',
  'The phenomenon of dark matter remains one of the unsolved mysteries in astrophysics.',
  'Social justice advocates for equal rights and opportunities for all members of society.',
  'The development of 5G technology promises faster and more reliable wireless communication.',
  'The cultural significance of traditional ceremonies reflects the rich heritage of communities.',
  'Human rights serve as a foundation for dignity, justice, and equality worldwide.',
  'In geology, plate boundaries are dynamic zones where tectonic plates interact.',
  'Advances in robotics contribute to applications ranging from manufacturing to healthcare.',
  'Hey, how\'s it going? Long time no see!',
  'I binge-watched that new series last night, it\'s so addictive.',
  'Pizza or tacos? I can never decide; they\'re both amazing.',
  'Guess what? I finally got that promotion at work!',
  'Don\'t stress about it, we\'ll figure it out together.',
  'Let\'s grab some coffee and catch up this weekend.',
  'I\'m on a mission to find the perfect burger in town.',
  'Life\'s too short for boring weekends. Let\'s plan an adventure!',
  'Ugh, Monday mornings are the worst, aren\'t they?',
  'Have you heard the latest gossip? It\'s juicy!',
  'I tried cooking a fancy recipe, but it turned into a kitchen disaster.',
  'Road trips are the best, especially with good music blasting.',
  'I totally lost track of time playing video games all night.',
  'Meeting new people can be awkward, but it\'s also kind of exciting.',
  'My pet just learned a new trick, and it\'s the cutest thing ever.',
  'Let\'s not adult today; responsibilities can wait.',
  'Why does choosing what to watch on Netflix take longer than the actual show?',
  'Did you see that viral cat video? It made my day.',
  'Coffee is my love language; I can\'t function without it.',
  'I need a vacation from adulting. Let\'s plan a getaway!',
  'Procrastination level: expert. I\'ll do it tomorrow, for sure.',
  'Those \'aha\' moments in life are pure gold.',
  'Sundays are made for lounging in pajamas and binge-eating snacks.',
  'Rainy days and a good book—a perfect combo.',
  'Friendship is when you can be weird together and not judge each other.',
  'I\'m officially on a shopping ban... until the next sale.',
  'The struggle of finding matching socks is too real.',
  'No Monday blues here; just gratitude for a new week.',
  'Being an adult is like folding a fitted sheet—nobody really knows how to do it.',
  'Can we just fast-forward to the weekend already?',
  'I\'m not a morning person. Coffee is my only motivation to wake up.',
  'Dance like nobody\'s watching; it\'s the best stress buster.',
  'Let\'s taco \'bout how awesome tacos are.',
  'When life gives you lemons, make a lemonade cocktail.',
  'You know it\'s true friendship when you can share food without hesitation.',
  'Cheers to the weekend and making questionable life choices!',
  'Pizza delivery is the real MVP on lazy evenings.',
  'Why do weekends fly by, but weekdays drag on forever?',
  'My bed is calling my name; it\'s time for a cozy nap.',
  'The secret to happiness: good food and good company.',
]);


const ptBR_training_sentences = new Set([
  'Processamento de linguagem natural é uma área de inteligência artificial.',
  'Redes neurais recorrentes são usadas para modelagem de sequências.',
  'A rápida raposa marrom pula sobre o cachorro preguiçoso.',
  'Algoritmos de aprendizado de máquina podem analisar conjuntos de dados grandes.',
  'A Internet das Coisas (IoT) conecta dispositivos à internet para troca de dados.',
  'A computação quântica tem o potencial de revolucionar a computação.',
  'Redes neurais artificiais tentam imitar a estrutura do cérebro humano.',
  'A linguagem de programação Python é amplamente usada em ciência de dados.',
  'A teoria da relatividade de Einstein transformou nossa compreensão do espaço e do tempo.',
  'Na visão computacional, redes neurais convolucionais se destacam em tarefas de reconhecimento de imagem.',
  'O projeto genoma humano visava sequenciar todo o DNA humano.',
  'A tecnologia blockchain é a base de criptomoedas como o Bitcoin.',
  'As peças de Shakespeare são consideradas clássicos atemporais.',
  'A mudança climática representa desafios significativos para os ecossistemas globais.',
  'A ONU busca a paz e cooperação internacional.',
  'Fontes de energia renovável, como solar e eólica, são essenciais para um futuro sustentável.',
  'A aprendizagem profunda alcançou sucesso notável em várias aplicações.',
  'A inteligência artificial tem implicações éticas que requerem cuidadosa consideração.',
  'O Renascimento foi um período de crescimento cultural e intelectual na Europa.',
  'Missões de exploração de Marte buscam entender a geologia do planeta vermelho e sua habitabilidade potencial.',
  'A teoria da evolução por seleção natural é uma pedra angular da biologia.',
  'A tecnologia de satélites permite comunicação global e sistemas de navegação.',
  'A World Wide Web foi inventada por Sir Tim Berners-Lee em 1989.',
  'A criptografia desempenha um papel crucial na segurança das comunicações digitais.',
  'O bóson de Higgs, frequentemente chamado de \'partícula de Deus\', foi descoberto no CERN.',
  'Civilizações antigas, como os egípcios e gregos, fizeram contribuições significativas para a história humana.',
  'A tradução automática tornou-se cada vez mais precisa com o advento de modelos de linguagem neurais.',
  'A tabela periódica organiza elementos químicos com base em suas propriedades e números atômicos.',
  'Epidemiologistas estudam a propagação e controle de doenças dentro de populações.',
  'A teoria da tectônica de placas explica o movimento das placas litosféricas da Terra.',
  'Avanços na mecânica quântica levaram ao desenvolvimento de tecnologias quânticas.',
  'A Revolução Industrial transformou a sociedade por meio de inovação tecnológica e industrialização.',
  'O conceito de zero é uma ideia matemática fundamental com raízes históricas profundas.',
  'A galáxia da Via Láctea é apenas uma das bilhões de galáxias no universo observável.',
  'A Quarta Revolução Industrial é caracterizada pela fusão de tecnologias que borraram as linhas entre domínios físicos, digitais e biológicos.',
  'O desenvolvimento do CRISPR-Cas9 revolucionou a edição genética e tem grande potencial na biotecnologia.',
  'E aí, como vai? Já faz um tempão!',
  'Maratonei aquela nova série ontem à noite, é viciante demais.',
  'Pizza ou tacos? Nunca consigo decidir, os dois são incríveis.',
  'Adivinha? Finalmente consegui aquela promoção no trabalho!',
  'Não se estresse com isso, a gente resolve junto.',
  'Vamos tomar um café e colocar o papo em dia neste fim de semana.',
  'Estou numa missão para encontrar o melhor hambúrguer da cidade.',
  'A vida é muito curta para fins de semana chatos. Vamos planejar uma aventura!',
  'Ai, as manhãs de segunda-feira são as piores, né?',
  'Você ouviu as últimas fofocas? Está bombando!',
  'Tentei cozinhar uma receita chique, mas virou um desastre na cozinha.',
  'Viagens de carro são as melhores, principalmente com música boa no volume máximo.',
  'Perdi completamente a noção do tempo jogando videogame a noite toda.',
  'Conhecer pessoas novas pode ser estranho, mas também é meio emocionante.',
  'Meu bichinho de estimação acabou de aprender um truque novo, é a coisa mais fofa!',
  'Vamos esquecer as responsabilidades hoje; adultar pode esperar.',
  'Por que escolher o que assistir na Netflix leva mais tempo do que o próprio programa?',
  'Você viu aquele vídeo de gato que viralizou? Alegrou o meu dia.',
  'Café é minha linguagem do amor; não consigo funcionar sem ele.',
  'Preciso de férias do mundo adulto. Vamos planejar uma escapada!',
  'Nível de procrastinação: expert. Vou fazer isso amanhã, com certeza.',
  'Aqueles momentos \'aha\' na vida são ouro puro.',
  'Domingos foram feitos para ficar de pijama e comer besteiras sem parar.',
  'Dias chuvosos e um bom livro—uma combinação perfeita.',
  'Amizade é quando você pode ser estranho junto sem julgamentos.',
  'Oficialmente estou em um banimento de compras... até a próxima liquidação.',
  'A luta para encontrar meias que combinam é real demais.',
  'Nada de tristeza na segunda-feira aqui; só gratidão por uma nova semana.',
  'Ser adulto é como dobrar um lençol com elástico—ninguém realmente sabe como fazer.',
  'Podemos pular direto para o fim de semana?',
  'Não sou uma pessoa matinal. Café é minha única motivação para acordar.',
  'Dançar como se ninguém estivesse olhando; é a melhor forma de aliviar o estresse.',
  'Vamos falar sobre o quão incríveis são os tacos.',
  'Quando a vida te dá limões, faça uma limonada com destilado.',
  'É verdadeira amizade quando você pode compartilhar comida sem hesitar.',
  'Saúde para o fim de semana e para as escolhas de vida questionáveis!',
  'Entrega de pizza é o verdadeiro herói nas noites preguiçosas.',
  'Por que os finais de semana passam voando, mas os dias úteis demoram uma eternidade?',
  'Minha cama está me chamando; é hora de uma soneca aconchegante.',
  'O segredo da felicidade: boa comida e boa companhia.',
]);


const mxES_training_sentences = new Set([
  'El procesamiento de lenguaje natural es un campo de la inteligencia artificial.',
  'Las redes neuronales recurrentes se utilizan para modelar secuencias.',
  'El rápido zorro marrón salta sobre el perro perezoso.',
  'Los algoritmos de aprendizaje automático pueden analizar conjuntos de datos grandes.',
  'La Internet de las cosas (IoT) conecta dispositivos a la internet para el intercambio de datos.',
  'La computación cuántica tiene el potencial de revolucionar la computación.',
  'Las redes neuronales artificiales intentan imitar la estructura del cerebro humano.',
  'El lenguaje de programación Python se utiliza ampliamente en ciencia de datos.',
  'La teoría de la relatividad de Einstein transformó nuestra comprensión del espacio y del tiempo.',
  'En la visión por computadora, las redes neuronales convolucionales destacan en tareas de reconocimiento de imagen.',
  'El proyecto del genoma humano tenía como objetivo secuenciar todo el ADN humano.',
  'La tecnología blockchain subyace a criptomonedas como Bitcoin.',
  'Las obras de Shakespeare son consideradas clásicos atemporales.',
  'El cambio climático plantea desafíos significativos para los ecosistemas globales.',
  'Las Naciones Unidas buscan la paz y la cooperación internacional.',
  'Fuentes de energía renovable, como la solar y eólica, son clave para un futuro sostenible.',
  'El aprendizaje profundo ha logrado un éxito notable en diversas aplicaciones.',
  'La inteligencia artificial tiene implicaciones éticas que requieren cuidadosa consideración.',
  'El Renacimiento fue un período de crecimiento cultural e intelectual en Europa.',
  'Las misiones de exploración de Marte buscan entender la geología del planeta rojo y su habitabilidad potencial.',
  'La teoría de la evolución por selección natural es fundamental en biología.',
  'La tecnología de satélites permite la comunicación global y sistemas de navegación.',
  'La World Wide Web fue inventada por Sir Tim Berners-Lee en 1989.',
  'La criptografía desempeña un papel crucial en la seguridad de las comunicaciones digitales.',
  'El bosón de Higgs, a menudo llamado la \'partícula de Dios\', fue descubierto en el CERN.',
  'Civilizaciones antiguas, como los egipcios y griegos, hicieron contribuciones significativas a la historia humana.',
  'Los epidemiólogos estudian la propagación y el control de enfermedades dentro de poblaciones.',
  'La teoría de la tectónica de placas explica el movimiento de las placas litosféricas de la Tierra.',
  'Avances en la mecánica cuántica han llevado al desarrollo de tecnologías cuánticas.',
  'La Revolución Industrial transformó la sociedad mediante la innovación tecnológica y la industrialización.',
  'El concepto de cero es una idea matemática fundamental con profundas raíces históricas.',
  'La galaxia de la Vía Láctea es solo una de las miles de millones de galaxias en el universo observable.',
  'La Cuarta Revolución Industrial se caracteriza por la fusión de tecnologías que difuminan las líneas entre dominios físicos, digitales y biológicos.',
  'El desarrollo de CRISPR-Cas9 ha revolucionado la edición genética y tiene un gran potencial en biotecnología.',
]);


const ptBR_mixed_topics_sentences = new Set([
  'A inteligência artificial está redefinindo a paisagem da tecnologia moderna.',
  'Influenciadores digitais são agora figuras proeminentes nas redes sociais.',
  'Realidade aumentada oferece experiências interativas e envolventes.',
  'Blockchain está transformando a maneira como lidamos com transações financeiras.',
  'O e-sports se tornou uma indústria multimilionária com competições globais.',
  'Tecnologias de assistência virtual estão facilitando a vida de muitas pessoas.',
  'O movimento maker incentiva a criação de projetos DIY e inovações.',
  'A impressão 3D está revolucionando a fabricação de protótipos e produtos.',
  'Empresas de fintech estão introduzindo soluções financeiras inovadoras.',
  'A cultura do teletrabalho está se consolidando como uma nova norma.',
  'Estratégias de marketing digital são cruciais para o sucesso de empresas online.',
  'A cibersegurança é uma preocupação crescente em um mundo digitalizado.',
  'Tendências de moda sustentável estão ganhando destaque na indústria.',
  'O comércio eletrônico transformou a maneira como fazemos compras.',
  'Drones têm aplicações versáteis, desde entretenimento até serviços de entrega.',
  'A realidade virtual no setor educacional melhora a aprendizagem imersiva.',
  'Redes neurais convolucionais impulsionam avanços na visão computacional.',
  'A Revolução Industrial teve um impacto profundo nas condições de trabalho.',
  'As antigas civilizações egípcias deixaram um legado duradouro na arquitetura.',
  'O renascimento artístico trouxe uma explosão de criatividade no século XV.',
  'A teoria da relatividade de Einstein revolucionou a física no século XX.',
  'A Revolução Francesa alterou radicalmente o cenário político e social.',
  'A invenção da roda foi um marco crucial na história da tecnologia.',
  'A Grécia antiga contribuiu significativamente para a filosofia e ciências.',
  'A Peste Negra teve um impacto devastador na população europeia medieval.',
  'A máquina a vapor foi um precursor crucial para a Revolução Industrial.',
  'A descoberta da penicilina revolucionou a medicina no século XX.',
  'A imprenta de Gutenberg facilitou a disseminação de conhecimento na Renascença.',
  'O código de Hamurabi é uma das primeiras leis escritas conhecidas.',
  'A Revolta da Chibata foi um evento significativo na história do Brasil.',
  'O desenvolvimento da bússola revolucionou as explorações marítimas.',
  'Quem não se lembra das brincadeiras de esconde-esconde na infância?',
  'Os gibis da Turma da Mônica fazem parte da memória afetiva de muitos.',
  'A receita da vovó para bolo de chocolate sempre é a melhor.',
  'Pular amarelinha era a diversão preferida nos intervalos da escola.',
  'Colecionar figurinhas de álbum era uma febre entre as crianças.',
  'O cheirinho de giz de cera traz lembranças das aulas de desenho.',
  'Desbravar o quintal em busca de tesouros era uma aventura inesquecível.',
  'Os brinquedos de LEGO eram o passatempo favorito das tardes chuvosas.',
  'A música da abertura de desenhos animados ainda fica na cabeça.',
  'Fazer castelos de areia na praia era o programa perfeito nas férias.',
  'O primeiro videogame marcou a entrada em uma nova era de entretenimento.',
  'O cheirinho de livros novos ainda é irresistível para os amantes da leitura.',
  'O telefone com fio era o meio de comunicação mais comum nas casas.',
  'As cartas escritas à mão traziam emoção em tempos de distância.',
  'O sabor do chiclete de bola nos remete às tardes ensolaradas.',
  'As fotos reveladas eram aguardadas com ansiedade depois das viagens.',
  'O apito do vendedor de pipoca trazia alegria às tardes no parque.',
  'As festas de aniversário com bolo e brigadeiro são memórias especiais.',
  'Andar de bicicleta sem as mãos era um grande feito na infância.',
  'O primeiro beijo na adolescência é sempre lembrado com nostalgia.',
  'O barulho do apito do sorveteiro era música para os ouvidos das crianças.',
  'A troca de figurinhas de álbum de futebol era uma tradição entre amigos.',
  'Os jogos de tabuleiro eram a opção perfeita para noites em família.',
]);

const enUS_mix_topics_sentences = new Set([
  'Artificial intelligence is reshaping the landscape of modern technology.',
  'Digital influencers are now prominent figures on social media.',
  'Augmented reality provides interactive and immersive experiences.',
  'Blockchain is transforming how we handle financial transactions.',
  'E-sports has become a multimillion-dollar industry with global competitions.',
  'Virtual assistant technologies are making life easier for many people.',
  'The maker movement encourages DIY projects and innovations.',
  '3D printing is revolutionizing prototype and product manufacturing.',
  'Fintech companies are introducing innovative financial solutions.',
  'The culture of remote work is becoming a new norm.',
  'Digital marketing strategies are crucial for the success of online businesses.',
  'Cybersecurity is a growing concern in a digitized world.',
  'Trends in sustainable fashion are gaining prominence in the industry.',
  'E-commerce has transformed the way we shop.',
  'Drones have versatile applications, from entertainment to delivery services.',
  'Virtual reality in education enhances immersive learning.',
  'Convolutional neural networks drive advancements in computer vision.',
  'The Industrial Revolution had a profound impact on working conditions.',
  'Ancient Egyptian civilizations left a lasting legacy in architecture.',
  'The artistic Renaissance brought an explosion of creativity in the 15th century.',
  'Einstein\'s theory of relativity revolutionized physics in the 20th century.',
  'The French Revolution radically altered the political and social landscape.',
  'The invention of the wheel was a crucial milestone in technological history.',
  'Ancient Greece contributed significantly to philosophy and sciences.',
  'The Black Death had a devastating impact on medieval European population.',
  'The steam engine was a crucial precursor to the Industrial Revolution.',
  'The discovery of penicillin revolutionized medicine in the 20th century.',
  'Gutenberg\'s printing press facilitated the spread of knowledge in the Renaissance.',
  'The Code of Hammurabi is one of the earliest known written laws.',
  'The Chibata Revolt was a significant event in Brazilian history.',
  'The development of the compass revolutionized maritime exploration.',
  'Who doesn\'t remember playing hide and seek in childhood?',
  'Mônica\'s comics are part of the emotional memory of many.',
  'Grandma\'s recipe for chocolate cake is always the best.',
  'Jumping hopscotch was the favorite pastime during school breaks.',
  'Collecting album stickers was a craze among children.',
  'The smell of crayons brings back memories of drawing classes.',
  'Exploring the backyard for treasures was an unforgettable adventure.',
  'LEGO toys were the favorite pastime on rainy afternoons.',
  'The music from cartoon openings still stays in the head.',
  'Building sandcastles on the beach was the perfect vacation activity.',
  'The first video game marked the entry into a new era of entertainment.',
  'The smell of new books is still irresistible for book lovers.',
  'The landline phone was the most common communication medium at home.',
  'Handwritten letters brought emotion in times of distance.',
  'The taste of bubblegum brings back memories of sunny afternoons.',
  'Revealed photos were eagerly awaited after trips.',
  'The popcorn vendor\'s whistle brought joy to afternoons in the park.',
  'Birthday parties with cake and brigadeiro are special memories.',
  'Riding a bike without hands was a great feat in childhood.',
  'The first kiss in adolescence is always remembered with nostalgia.',
  'The ice cream vendor\'s bell was music to children\'s ears.',
  'Swapping football album stickers was a tradition among friends.',
  'Board games were the perfect option for family nights.',
]);


const privateSentences = new Set([
  'Artificial intelligence is transforming industries worldwide.',
  'La réalité virtuelle offre des expériences immersives uniques.',
  'Tech startups are driving innovation in urban mobility.',
  'O avanço da medicina regenerativa promete revolucionar tratamentos de saúde.',
  'Social media influencers impact consumer trends and preferences.',
  'Die Klimakrise erfordert dringende Maßnahmen für eine nachhaltige Zukunft.',
  'SpaceX\'s achievements mark a new era in space exploration.',
  'Elon Musk\'s vision for a high-speed Hyperloop challenges traditional transportation.',
  'A inteligência artificial está mudando a forma como interagimos com dispositivos eletrônicos.',
  'La inteligencia artificial está transformando la atención médica y diagnósticos.',
  'Cryptocurrency and blockchain are reshaping the financial landscape.',
  'Sustainable fashion practices aim to reduce the environmental impact of the industry.',
  'A robótica colaborativa está otimizando processos de fabricação em diversas indústrias.',
  'La biotecnología abre nuevas posibilidades en la agricultura y la medicina.',
  'Quantum computing holds the potential for solving complex problems at unprecedented speeds.',
  'A realidade aumentada está sendo utilizada em aplicações educacionais inovadoras.',
  'The Renaissance period witnessed a flourishing of arts, science, and culture.',
  'Die industrielle Revolution veränderte die Art und Weise, wie Menschen arbeiteten und lebten.',
  'O Império Romano deixou um legado duradouro na arquitetura e governo.',
  'La Revolución Mexicana marcó un punto de inflexión en la historia de México.',
  'Ancient Chinese inventions, like paper and the compass, revolutionized civilization.',
  'A Revolução Russa de 1917 teve impactos significativos no curso da história mundial.',
  'The Age of Enlightenment emphasized reason, science, and individual rights.',
  'La Guerra Civil Americana fue un conflicto que marcó un cambio en la nación.',
  'A Revolução dos Cravos em Portugal trouxe liberdade após anos de ditadura.',
  'La Revolución Industrial transformó la producción y la vida cotidiana.',
  'The Silk Road facilitated cultural exchange between East and West.',
  'A descoberta da penicilina por Alexander Fleming revolucionou a medicina moderna.',
  'Die Entdeckung der Dampfmaschine durch James Watt trieb die industrielle Revolution voran.',
  'A descoberta das Américas por Cristóvão Colombo abriu novas rotas comerciais.',
  'Die Magna Carta legte den Grundstein für die Entwicklung von Rechtsprinzipien.',
  'A Revolta da Chibata no Brasil foi um movimento pela melhoria das condições na Marinha.',
  'Playing hopscotch and jump rope were favorite childhood pastimes.',
  'Les poupées Barbie ont été une icône de la mode pour de nombreuses générations.',
  'A aventura do Ursinho Pooh encanta crianças de todas as idades.',
  'Scooby-Doo, Where Are You! remains a classic animated series loved by many.',
  'Collecting Pokémon cards was a craze in the \'90s and 2000s.',
  'As brincadeiras de esconde-esconde nunca saem de moda.',
  'Los juguetes LEGO han estimulado la creatividad de generaciones de niños.',
  'Pular elástico e brincar de pique-esconde são tradições de infância.',
  'Cinderella\'s glass slipper is an iconic symbol in fairy tales.',
  'O cheiro de giz de cera evoca lembranças de desenhos coloridos na infância.',
  'Disneyland is the happiest place on earth for many families.',
  'A bicicleta sem rodinhas é um marco emocionante na infância.',
  'Building sandcastles on the beach is a timeless summer activity.',
  'Les premiers pas sur la lune ont captivé le monde entier en 1969.',
  'Os carrinhos de controle remoto proporcionam diversão para todas as idades.',
  'Saturday morning cartoons were a weekly delight for kids.',
  'As memórias do primeiro beijo são especiais e memoráveis.',
  'The smell of freshly baked cookies is a comforting childhood memory.',
  'O esconde-esconde noturno trazia emoção às brincadeiras ao ar livre.',
  'Cartoons like Tom and Jerry continue to entertain new generations.',
  'The joy of blowing bubbles transcends age.',
  'Os quebra-cabeças desafiam a mente e proporcionam horas de entretenimento.',
  'Recuerdos de la infancia: el sonido del camión de helados anunciando su llegada.',
  'A maratona de desenhos animados é uma tradição preguiçosa de domingo.',
  'Morning coffee is the daily ritual that kickstarts productivity.',
  'Les petits plaisirs de la vie incluent un bon livre et une tasse de thé.',
  'The smell of rain on hot pavement is a refreshing scent after a summer storm.',
  'Fazer uma lista de tarefas é uma estratégia eficaz para organizar o dia.',
  'La cocina es el corazón del hogar, donde se comparten comidas y recuerdos.',
  'Sunday brunch is the perfect way to relax and enjoy good food.',
  'Taking a walk in nature has a calming effect on the mind.',
  'Die Klänge der Natur, wie das Rauschen des Meeres, haben eine beruhigende Wirkung.',
  'Listening to a favorite song can instantly lift the mood.',
  'Cooking together with loved ones creates special moments in the kitchen.',
  'Laughter is a universal language that brings people together.',
  'L\'odeur du pain frais sortant du four est irrésistible.',
  'Eine warme Dusche am Ende eines langen Tages ist eine Wohltat.',
  'Cada puesta de sol es única y ofrece un espectáculo visual impresionante.',
  'Un bon repas partagé avec des amis crée des souvenirs durables.',
  'Binge-watching a favorite TV series is a guilty pleasure for many.',
  'A hug can convey emotions and support without words.',
  'The sound of waves crashing on the shore is a soothing lullaby.',
  'Lire un bon livre sous une couverture chaude est un plaisir simple.',
  'Cooking a homemade meal is a rewarding and therapeutic experience.',
  'Die ersten Sonnenstrahlen am Morgen bringen Energie und Hoffnung.',
  'The joy of receiving a handwritten letter in the mail is timeless.',
  'Gardening provides a sense of accomplishment and connection to nature.',
  'Die Stille eines Waldes lädt dazu ein, zur inneren Ruhe zu finden.',
  'Baking cookies fills the kitchen with warmth and sweetness.',
  'Street art adds a vibrant and dynamic touch to urban landscapes.',
  'La danza es una forma expresiva de arte que trasciende barreras lingüísticas.',
  'Theatrical performances capture the essence of storytelling in a live setting.',
  'O cinema é uma forma poderosa de contar histórias e criar empatia.',
  'Die Architektur von Gaudí in Barcelona ist eine Fusion von Fantasie und Realität.',
  'Reading poetry is a journey into the beauty of language and emotions.',
  'La música clásica tiene la capacidad de evocar emociones profundas.',
  'Art museums showcase diverse perspectives and creative expression.',
  'La moda es una forma de expresión personal y cultural.',
  'Photography freezes moments in time, preserving memories forever.',
  'Theater productions bring characters to life on stage with passion and skill.',
  'La gastronomía es una expresión artística que deleita los sentidos.',
  'Abstract art challenges perception and invites interpretation.',
  'La literatura fantástica transporta a los lectores a mundos imaginarios.',
  'Cultural festivals celebrate diversity and foster community bonds.',
  'Die Musikgeschichte ist reich an verschiedenen Genres und Einflüssen.',
  'La poesía spoken word combina la palabra hablada con la musicalidad del lenguaje.',
  'Street food markets offer a culinary adventure of flavors and aromas.',
  'Die Kleidung eines Menschen kann viel über seine Persönlichkeit aussagen.',
  'Dance forms like salsa and tango reflect cultural richness and passion.',
  'La arquitectura moderna desafía las convenciones y busca la innovación.',
  'Cinema noir captures the essence of mystery and intrigue in film.',
  'Die Oper ist eine kraftvolle Verbindung von Musik, Gesang und Schauspiel.',
  'La pintura al óleo permite a los artistas explorar texturas y colores vibrantes.',
  'Die Welt der Videospiele ist ein interaktives Medium der kreativen Unterhaltung.',
  'The beauty of calligraphy lies in the artistry of written language.',
  'Climate change requires global cooperation for sustainable solutions.',
  'La igualdad de género es fundamental para construir sociedades justas e inclusivas.',
  'Social media activism amplifies voices and drives social change.',
  'La educación accesible es un derecho fundamental para el desarrollo de la sociedad.',
  'Global health initiatives aim to address disparities and improve well-being.',
  'La diversidad cultural enriquece nuestras comunidades y promueve la comprensión.',
  'Eradicating poverty requires comprehensive efforts and social policies.',
  'Die Flüchtlingskrise erfordert eine koordinierte Antwort und Mitgefühl.',
  'Access to clean water is a basic human right for communities worldwide.',
  'La lucha contra la discriminación racial es esencial para la justicia social.',
  'Promoting mental health awareness reduces stigma and fosters support.',
  'La preservación de la biodiversidad es crucial para el equilibrio ecológico.',
  'Die Bekämpfung von Hunger erfordert nachhaltige landwirtschaftliche Praktiken.',
  'Ensuring quality education for all is key to breaking the cycle of poverty.',
  'La tecnología puede ser una herramienta poderosa para cerrar la brecha educativa.',
  'Combating human trafficking requires international cooperation and awareness.',
  'La equidad en la distribución de recursos es esencial para la estabilidad global.',
  'Empowering women economically contributes to sustainable development.',
  'La paz mundial se construye a través del diálogo y la resolución pacífica de conflictos.',
  'Promoting sustainable consumption practices mitigates environmental impact.',
  'La participación ciudadana fortalece la democracia y la rendición de cuentas.',
  'Addressing mental health challenges is crucial for overall well-being.',
  'La cooperación internacional es fundamental para abordar problemas globales.',
  'Promoting cultural tolerance fosters harmony in diverse societies.',
  'La innovación tecnológica puede impulsar soluciones creativas para desafíos mundiales.',
  'Sustainable urban planning enhances the quality of life in cities.',
  'La protección de los derechos humanos es esencial para la dignidad y la justicia.',
  'Bananas are berries, while strawberries are not technically berries.',
  'Oxford University predates the Aztec Empire by several centuries.',
  'Honey never spoils; archaeologists have found edible honey in ancient tombs.',
  'A blue whale\'s heart is so large that a human could swim through its arteries.',
  'Koalas have unique fingerprints similar to those of humans.',
  'The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.',
  'A group of flamingos is called a \'flamboyance.\'',
  'The Great Wall of China is not visible from space with the naked eye.',
  'Cows have best friends and can become stressed when separated from them.',
  'Elephants are the only animals that can\'t jump.',
  'Honeybees can recognize human faces.',
  'A \'jiffy\' is an actual unit of time, equivalent to 1/100th of a second.',
  'Octopuses have three hearts and blue blood.',
  'Wombat poop is cube-shaped to prevent it from rolling away.',
  'The world\'s largest desert is Antarctica.',
  'The shortest war in history was between Britain and Zanzibar, lasting only 38 minutes.',
  'The original name of Bank of America was \'Bank of Italy.\'',
  'There are more possible iterations of a game of chess than there are atoms in the known universe.',
  'Coca-Cola originally contained cocaine until 1929.',
  'The dot over the letter \'i\' is called a tittle.',
  'The longest word without a vowel is \'rhythms.\'',
  'A group of owls is called a \'parliament.\'',
  'The average person will spend six months of their life waiting for red lights to turn green.',
  'Banging your head against a wall burns about 150 calories per hour.',
  'The word \'nerd\' was first coined by Dr. Seuss in \'If I Ran the Zoo.\'',
  'There are more possible iterations of a game of chess than there are atoms in the known universe.',
  'A inteligência artificial está transformando a forma como vivemos.',
  'Os influenciadores digitais têm grande impacto nas redes sociais.',
  'A realidade virtual oferece experiências imersivas incríveis.',
  'A criptomoeda está mudando a dinâmica financeira global.',
  'O streaming de música revolucionou a maneira como ouvimos músicas.',
  'Startups estão inovando em diversos setores da economia.',
  'A cultura do coworking está ganhando popularidade.',
  'A sustentabilidade no design é uma abordagem essencial.',
  'O comércio eletrônico transformou a maneira como fazemos compras.',
  'A robótica avançada está otimizando processos industriais.',
  'A cibersegurança é uma preocupação constante na era digital.',
  'Tecnologias de assistência virtual estão facilitando a vida diária.',
  'A moda sustentável é uma tendência crescente no mundo da moda.',
  'O teletrabalho tornou-se uma prática comum em muitas empresas.',
  'Drones estão sendo utilizados em diversas aplicações.',
  'A realidade aumentada está sendo aplicada na educação.',
  'Redes neurais convolucionais impulsionam avanços na tecnologia.',
  'A Revolução Industrial transformou a sociedade no século XIX.',
  'As antigas civilizações egípcias deixaram um legado duradouro.',
  'O Renascimento artístico trouxe uma explosão de criatividade.',
  'A teoria da relatividade de Einstein revolucionou a física.',
  'A Revolução Francesa marcou uma mudança radical na política.',
  'A invenção da roda foi um marco na evolução tecnológica.',
  'A Grécia antiga contribuiu significativamente para a filosofia.',
  'A Peste Negra teve um impacto devastador na população medieval.',
  'A máquina a vapor foi crucial para a Revolução Industrial.',
  'A descoberta da penicilina revolucionou a medicina moderna.',
  'A imprensa de Gutenberg facilitou a disseminação do conhecimento.',
  'O código de Hamurabi é uma das primeiras leis escritas.',
  'A Revolta da Chibata foi um movimento por melhores condições.',
  'O desenvolvimento da bússola impulsionou as explorações marítimas.',
  'Quem não se lembra das brincadeiras de rua na infância?',
  'Os gibis da Turma da Mônica são clássicos da infância.',
  'A receita da vovó para bolo de chocolate é imbatível.',
  'Pular amarelinha era a diversão preferida nos intervalos.',
  'Colecionar figurinhas de álbum era uma febre entre as crianças.',
  'O cheirinho de giz de cera traz lembranças das aulas de desenho.',
  'Explorar o quintal em busca de tesouros era uma aventura.',
  'Os brinquedos de LEGO eram a diversão nas tardes chuvosas.',
  'A música da abertura dos desenhos animados é inesquecível.',
  'Fazer castelos de areia na praia era o programa perfeito.',
  'O primeiro videogame marcou o início de uma nova era.',
  'O cheirinho de livros novos ainda é irresistível.',
  'O telefone com fio era o meio de comunicação comum em casa.',
  'As cartas escritas à mão eram carregadas de emoção.',
  'O sabor do chiclete de bola remete à infância ensolarada.',
  'As fotos reveladas eram aguardadas com ansiedade.',
  'O apito do vendedor de pipoca trazia alegria às tardes.',
  'As festas de aniversário com bolo e brigadeiro eram especiais.',
  'Andar de bicicleta sem as mãos era uma grande conquista.',
  'O primeiro beijo na adolescência é sempre lembrado.',
  'O barulho do apito do sorveteiro era música para os ouvidos.',
  'A troca de figurinhas de álbum de futebol era uma tradição.',
  'Os jogos de tabuleiro eram perfeitos para noites em família.',
  'O café da manhã é o ritual diário que energiza o dia.',
  'Pequenos prazeres incluem um bom livro e uma xícara de chá.',
  'O cheiro da chuva no asfalto quente é refrescante após a tempestade.',
  'Fazer uma lista de tarefas é uma estratégia eficaz para organizar o dia.',
  'A cozinha é o coração da casa, onde se compartilham refeições e memórias.',
  'O brunch de domingo é a maneira perfeita de relaxar e saborear boa comida.',
  'Dar um passeio na natureza tem um efeito calmante na mente.',
  'Os sons da natureza, como o ruído do mar, têm um efeito tranquilizador.',
  'Ouvir uma música favorita pode elevar instantaneamente o humor.',
  'Cozinhar junto com entes queridos cria momentos especiais na cozinha.',
  'O riso é uma linguagem universal que une as pessoas.',
  'O cheiro do pão fresco saindo do forno é irresistível.',
  'Um banho quente no final do dia é um verdadeiro deleite.',
  'Cada pôr do sol é único e oferece um espetáculo visual impressionante.',
  'Uma boa refeição compartilhada com amigos cria memórias duradouras.',
  'Assistir a uma maratona de séries é um prazer culpado para muitos.',
  'Um abraço pode transmitir emoções e apoio sem palavras.',
  'O som das ondas quebrando na costa é uma canção de ninar relaxante.',
  'Ler um bom livro sob uma coberta quente é um prazer simples.',
  'Cozinhar uma refeição caseira é uma experiência recompensadora.',
  'Os primeiros raios de sol da manhã trazem energia e esperança.',
  'A alegria de receber uma carta escrita à mão pelo correio é atemporal.',
  'A jardinagem proporciona uma sensação de realização e conexão com a natureza.',
  'A tranquilidade de uma floresta convida à busca pela paz interior.',
  'Assar biscoitos enche a cozinha com calor e doçura.',
  'A arte de rua adiciona um toque vibrante e dinâmico às paisagens urbanas.',
  'A dança é uma forma expressiva de arte que transcende barreiras linguísticas.',
  'As performances teatrais capturam a essência da narrativa em um ambiente ao vivo.',
  'O cinema é uma forma poderosa de contar histórias e criar empatia.',
  'A arquitetura de Gaudí em Barcelona é uma fusão de fantasia e realidade.',
  'Ler poesia é uma jornada à beleza da linguagem e das emoções.',
  'A música clássica tem a capacidade de evocar emoções profundas.',
  'Museus de arte mostram perspectivas diversas e expressão criativa.',
  'A moda é uma forma de expressão pessoal e cultural.',
  'A fotografia congela momentos no tempo, preservando memórias para sempre.',
  'As produções teatrais dão vida a personagens no palco com paixão e habilidade.',
  'A gastronomia é uma expressão artística que encanta os sentidos.',
  'A arte abstrata desafia a percepção e convida à interpretação.',
  'A literatura fantástica transporta leitores para mundos imaginários.',
  'Festivais culturais celebram a diversidade e fortalecem laços comunitários.',
  'A história da música é rica em diferentes gêneros e influências.',
  'A poesia falada combina a palavra com a musicalidade da linguagem.',
  'Os mercados de comida de rua oferecem uma aventura culinária de sabores e aromas.',
  'A roupa de uma pessoa pode dizer muito sobre sua personalidade.',
  'Danças como salsa e tango refletem a riqueza cultural e a paixão.',
  'A arquitetura moderna desafia convenções e busca inovação.',
  'O cinema noir captura a essência de mistério e intriga no cinema.',
  'A ópera é uma poderosa combinação de música, canto e atuação.',
  'A pintura a óleo permite aos artistas explorar texturas e cores vibrantes.',
  'O mundo dos videogames é um meio interativo de entretenimento criativo.',
  'A beleza da caligrafia está na arte da linguagem escrita.',
  'A mudança climática exige cooperação global para soluções sustentáveis.',
  'A igualdade de gênero é fundamental para construir sociedades justas e inclusivas.',
  'O ativismo nas redes sociais amplifica vozes e impulsiona a mudança social.',
  'A educação acessível é um direito fundamental para o desenvolvimento da sociedade.',
  'Iniciativas globais de saúde visam abordar disparidades e melhorar o bem-estar.',
  'A diversidade cultural enriquece nossas comunidades e promove a compreensão.',
  'Erradicar a pobreza requer esforços abrangentes e políticas sociais.',
  'A crise dos refugiados exige uma resposta coordenada e compassiva.',
  'O acesso à água limpa é um direito humano básico para comunidades em todo o mundo.',
  'A luta contra a discriminação racial é essencial para a justiça social.',
  'Promover a conscientização sobre saúde mental reduz o estigma e fomenta o apoio.',
  'A preservação da biodiversidade é crucial para o equilíbrio ecológico.',
  'Combater a fome requer práticas agrícolas sustentáveis.',
  'Garantir uma educação de qualidade para todos é fundamental para quebrar o ciclo da pobreza.',
  'A tecnologia pode ser uma ferramenta poderosa para fechar a lacuna educacional.',
  'Combater o tráfico humano requer cooperação internacional e conscientização.',
  'A equidade na distribuição de recursos é essencial para a estabilidade global.',
  'Empoderar economicamente as mulheres contribui para o desenvolvimento sustentável.',
  'A paz mundial é construída por meio do diálogo e da resolução pacífica de conflitos.',
  'Promover práticas de consumo sustentável mitiga o impacto ambiental.',
  'A participação cidadã fortalece a democracia e a responsabilidade.',
  'Enfrentar os desafios de saúde mental é crucial para o bem-estar geral.',
  'A cooperação internacional é fundamental para abordar problemas globais.',
  'Promover a tolerância cultural fomenta a harmonia em sociedades diversas.',
  'A inovação tecnológica pode impulsionar soluções criativas para desafios mundiais.',
  'O planejamento urbano sustentável melhora a qualidade de vida nas cidades.',
  'A proteção dos direitos humanos é essencial para a dignidade e a justiça.',
  'As bananas são consideradas frutas, enquanto morangos não são tecnicamente berries.',
  'A Universidade de Oxford antecede o Império Asteca por vários séculos.',
  'O mel nunca estraga; arqueólogos encontraram mel comestível em túmulos antigos.',
  'O coração de uma baleia-azul é tão grande que um humano poderia nadar por suas artérias.',
  'Coalas têm impressões digitais únicas semelhantes às dos humanos.',
  'A Torre Eiffel pode ficar 15 cm mais alta durante o verão devido à expansão térmica.',
  'Um grupo de flamingos é chamado de \'flamboyance\'.',
  'A Grande Muralha da China não é visível do espaço a olho nu.',
  'As vacas têm melhores amigos e podem ficar estressadas quando separadas deles.',
  'Elefantes são os únicos animais que não conseguem pular.',
  'Abelhas podem reconhecer rostos humanos.',
  'Um \'jiffy\' é uma unidade de tempo real, equivalente a 1/100 de segundo.',
  'Polvos têm três corações e sangue azul.',
  'As fezes de wombats têm formato de cubo para evitar que rolem.',
  'O deserto mais extenso do mundo é a Antártida.',
  'A guerra mais curta da história foi entre Grã-Bretanha e Zanzibar, durando apenas 38 minutos.',
  'O nome original do Bank of America era \'Bank of Italy\'.',
  'Existem mais iterações possíveis em uma partida de xadrez do que átomos no universo conhecido.',
  'A Coca-Cola originalmente continha cocaína até 1929.',
  'O ponto sobre a letra \'i\' é chamado de \'tittle\'.',
  'A palavra mais longa sem vogal é \'rhythms\'.',
  'Um grupo de corujas é chamado de \'parliament\'.',
  'A pessoa média passará seis meses de sua vida esperando sinais de trânsito ficarem verdes.',
  'Bater a cabeça contra uma parede queima cerca de 150 calorias por hora.',
  'A palavra \'nerd\' foi cunhada pela primeira vez pelo Dr. Seuss em \'If I Ran the Zoo\'.',
  'Existem mais iterações possíveis em uma partida de xadrez do que átomos no universo conhecido.',
]);



export const enUSTrainingSentences = Object.freeze([...enUS_training_sentences]) as readonly string[];

export const ptBRTrainingSentences = Object.freeze([...ptBR_training_sentences]) as readonly string[];

export const mxESTrainingSentences = Object.freeze([...mxES_training_sentences]) as readonly string[];

export const ptBRMixedTopicsSentences = Object.freeze([...ptBR_mixed_topics_sentences]) as readonly string[];

export const enUSMixedTopicsSentences = Object.freeze([...enUS_mix_topics_sentences]) as readonly string[];


export const sentencesWordlist = Object.freeze([...(new Set([
  ...enUS_training_sentences,
  ...ptBR_training_sentences,
  ...mxES_training_sentences,
  ...ptBR_mixed_topics_sentences,
  ...enUS_mix_topics_sentences,
  ...privateSentences,
]))]) as readonly string[];

export default sentencesWordlist;
